version: '3'

services:
  app:
    image: login:0.0.1
    build:
      context: .
      dockerfile: ./container/Dockerfile
      args:
        - SOURE_DIR=/usr/src/app
    environment:
      - PORT=80
    
    volumes:
      - .:/usr/src/app
    ports:
      - 30080:80
