version: '3'

services:
  app:
    image: login:0.0.1
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - SOURE_DIR=/usr/src/app
    environment:
      - PORT=80
      - NODE_ENV=container
    
    volumes:
      - .:/usr/src/app
    ports:
      - 30080:80

    networks:
      - our_net
    depends_on:
      - db

  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=test1234
    
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - 3306:3306
    expose:
      - 3306

    networks:
      - our_net

networks:
  our_net:
    driver: bridge
