version: '3'

services:
  app:
    image: auth:0.0.1
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
      args:
        - WOKR_DIR=/usr/app/src
    environment:
      - PORT=8001
      - NODE_ENV=container
      - KAKAO_REST_API_KEY=${KAKAO_REST_API_KEY}

    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        npx sequelize db:create
        npm i && npm start

    volumes:
      - ../src:/usr/app/src
    ports:
      - 8001:8001

    networks:
      - auth-net
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=test1234
    
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - 3306:3306

    networks:
      - auth-net

    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 3

networks:
  auth-net:
