version: '3'

services:
  app:
    image: auth:0.0.1
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
      args:
        - WOKR_DIR=/usr/app/src
    environment:
      - PORT=80
      - NODE_ENV=container

    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        npx sequelize db:create
        npm start

    volumes:
      - .:/usr/app/src
    ports:
      - 30080:80

    networks:
      - auth-net
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=test1234
    
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - 3306:3306

    networks:
      - auth-net

    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 3

networks:
  auth-net:
